name: Build and deploy to Firebase

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: macOS-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCHEDCARE }}'
          channelId: live
          projectId: schedcare
